#!/usr/bin/env bash
# ──────────────────────────────────────────────
#   install.sh — set up the dotfiles on a fresh Arch + Hyprland install.
#
#   What it does:
#     1. Backs up any existing config dirs that would be replaced.
#     2. Symlinks every app config from <repo>/config/ into ~/.config/.
#     3. Symlinks shell files (zshrc, bashrc, ...) into $HOME.
#     4. Sets up the active-theme symlink chain (defaults to "Noro").
#     5. Clones the wallpaper collections repo and installs the per-theme
#        sets into ~/.local/share/wallpapers (the XDG data location all scripts use).
#     6. Regenerates the matugen color palette from the current wallpaper.
#
#   Safe to re-run: existing symlinks are refreshed, backups are only
#   taken for real (non-symlink) files that are about to be replaced.
# ──────────────────────────────────────────────

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKUP_DIR="$HOME/.config-backup-$(date +%Y%m%d-%H%M%S)"
ACTIVE_THEME="${ACTIVE_THEME:-Noro}"
THEME_LOWER="$(printf '%s' "$ACTIVE_THEME" | tr '[:upper:]' '[:lower:]')"

info()  { printf '  \033[1;32m==>\033[0m %s\n' "$*"; }
warn()  { printf '  \033[1;33m ->\033[0m %s\n' "$*"; }

# ── 0. Privilege pre-flight ────────────────────
# A dangling SUDO_ASKPASS (e.g. left over from another dotfiles setup) makes
# every sudo call fail in non-interactive runs, so drop it if unusable.
if [ -n "${SUDO_ASKPASS:-}" ] && [ ! -x "$SUDO_ASKPASS" ]; then
    warn "SUDO_ASKPASS=$SUDO_ASKPASS is not executable, unsetting it"
    unset SUDO_ASKPASS
fi
# Cache sudo credentials once (prompts in a terminal); if that fails, skip
# all privileged steps gracefully instead of erroring on each one.
# NOTE: the non-interactive check (-n) comes first so piped/CI runs fail
# fast instead of blocking forever on a password prompt.
SUDO_OK=0
if sudo -n -v 2>/dev/null; then
    SUDO_OK=1                                   # cached credentials / NOPASSWD
elif [ -t 0 ]; then
    if sudo -v; then                            # interactive: ask once up front
        SUDO_OK=1
    else
        warn "sudo authentication failed — privileged steps will be skipped"
    fi
else
    warn "sudo needs a password and stdin is not a terminal — privileged steps will be skipped"
fi

# Install packages one at a time so a single failure (conflict, removed
# package, build error) never aborts the rest. Failed names are collected
# in FAILED_PKGS and reported at the end with an exact retry command.
FAILED_PKGS=""
install_pkgs() {
    local installer="$1"; shift
    local pkg
    for pkg in "$@"; do
        [ -n "$pkg" ] || continue
        # shellcheck disable=SC2086
        if $installer --noconfirm --needed "$pkg"; then
            info "installed $pkg"
        else
            FAILED_PKGS="$FAILED_PKGS $pkg"
            warn "FAILED: $pkg (continuing with the rest)"
        fi
    done
}
# Print the pkglist file as clean sorted LINES (no blanks/comments) —
# keep it line-based: comm(1) needs one package per line.
pkglist_lines() { grep -v -e '^[[:space:]]*$' -e '^[[:space:]]*#' "$1" | sort -u; }

# ── 1. App configs → ~/.config ────────────────
link_config() {
    local name="$1"
    local src="$REPO_ROOT/config/$name"
    local dst="$HOME/.config/$name"

    [ -d "$src" ] || { warn "skip $name (not in repo)"; return; }
    mkdir -p "$HOME/.config"

    if [ -L "$dst" ]; then
        rm "$dst"                                   # refresh existing symlink
    elif [ -e "$dst" ]; then
        mkdir -p "$BACKUP_DIR"
        mv "$dst" "$BACKUP_DIR/$name"
        warn "backed up existing $name -> $BACKUP_DIR/$name"
    fi
    ln -s "$src" "$dst"
    info "linked $name"
}

# App dirs versioned in this repo.
APPS=(
    hypr
    waybar
    rofi
    kitty
    btop
    matugen
    nvim
    zed
    swaync
    gtk-3.0
    gtk-4.0
)

# Apps whose only config is generated by matugen at runtime — just make sure
# the dir exists so the templates have somewhere to write.
# (swaync ships a versioned config.json; its style.css is matugen-generated.)
GENERATED_APPS=(
    fastfetch
    ghostty
    helium-theme
    swaync
)

echo "==> Linking app configs into ~/.config"
for app in "${APPS[@]}"; do
    link_config "$app"
done

# Generated-only apps: ensure their ~/.config dirs exist (matugen writes here).
for app in "${GENERATED_APPS[@]}"; do
    mkdir -p "$HOME/.config/$app"
    info "prepared $app (config generated by matugen)"
done

# ── 2. Shell files → $HOME ───────────────────
link_home() {
    local name="$1"                 # name inside repo shell/
    local dotname=".$1"             # name in $HOME, case-adjusted below
    local src="$REPO_ROOT/shell/$name"
    local dst="$HOME/$dotname"

    [ -f "$src" ] || { warn "skip $name (not in repo)"; return; }

    if [ -L "$dst" ]; then
        rm "$dst"
    elif [ -e "$dst" ]; then
        mkdir -p "$BACKUP_DIR"
        mv "$dst" "$BACKUP_DIR/$dotname"
        warn "backed up existing $dotname -> $BACKUP_DIR/$dotname"
    fi
    ln -s "$src" "$dst"
    info "linked $dotname"
}

echo
echo "==> Linking shell files into \$HOME"
link_home zshrc
link_home bashrc
link_home bash_profile
link_home dircolors
link_home gitconfig

# ── 3. Active theme symlink chain ────────────
echo
echo "==> Setting active theme: $ACTIVE_THEME"
HYPR_CFG="$HOME/.config/hypr"
WAYBAR_CFG="$HOME/.config/waybar"
ROFI_CFG="$HOME/.config/rofi"

if [ -f "$HYPR_CFG/themes/$THEME_LOWER/theme.conf" ]; then
    ln -sf "$HYPR_CFG/themes/$THEME_LOWER/theme.conf" "$HYPR_CFG/theme.conf"
    ln -sf "$HYPR_CFG/themes/$THEME_LOWER/theme.lua"  "$HYPR_CFG/theme.lua"
    ln -sf "$WAYBAR_CFG/themes/$THEME_LOWER/config.jsonc" "$WAYBAR_CFG/config.jsonc"
    ln -sf "$WAYBAR_CFG/themes/$THEME_LOWER/style.css"    "$WAYBAR_CFG/style.css"
    ln -sf "$ROFI_CFG/themes/$THEME_LOWER/launcher.rasi"  "$ROFI_CFG/active-launcher.rasi"
    ln -sf "$ROFI_CFG/themes/$THEME_LOWER/scripts.rasi"   "$ROFI_CFG/active-scripts.rasi"
    ln -sf "$ROFI_CFG/themes/$THEME_LOWER/picker.rasi"    "$ROFI_CFG/active-picker.rasi"
    printf '%s\n' "$ACTIVE_THEME" > "$HYPR_CFG/.active-theme"
    info "theme chain linked ($THEME_LOWER)"
else
    warn "theme '$ACTIVE_THEME' not found, leaving existing chain"
fi

# ── 4. Wallpapers → ~/.local/share/wallpapers ─
# Wallpapers live in their own repo (keeps this one small). Clone it once,
# then copy only the per-theme collection dirs — the pickers scan one level
# deep, so extra top-level dirs (optimized/, docs) must not leak in.
echo
echo "==> Installing wallpaper collections"
WALL_SRC="${WALLPAPER_SOURCE:-$HOME/.local/share/wallpapers-upstream}"
WALL_REPO="https://github.com/rajan9884/wallpapers.git"
if [ -d "$WALL_SRC/.git" ]; then
    git -C "$WALL_SRC" pull --ff-only >/dev/null 2>&1 \
        && info "wallpaper repo updated" \
        || warn "wallpaper repo pull failed, using cached copy"
elif [ -e "$WALL_SRC" ]; then
    warn "wallpaper source exists but is not a git repo, using it as-is: $WALL_SRC"
else
    git clone --depth 1 "$WALL_REPO" "$WALL_SRC" >/dev/null 2>&1 \
        && info "wallpaper repo cloned" \
        || warn "wallpaper repo clone failed (offline?) — pickers will fall back to existing ~/.local/share/wallpapers"
fi
WALL_DST="$HOME/.local/share/wallpapers"
mkdir -p "$WALL_DST"
for theme in glass material modern noro retro; do
    if [ -d "$WALL_SRC/$theme" ]; then
        mkdir -p "$WALL_DST/$theme"
        cp -p "$WALL_SRC/$theme"/* "$WALL_DST/$theme/" 2>/dev/null || true
        info "wallpapers: $theme ($(ls "$WALL_DST/$theme" | wc -l) files)"
    else
        warn "wallpapers: '$theme' not in source, skipping"
    fi
done

# ── 5. Executable bits ───────────────────────
echo
echo "==> Ensuring helper scripts are executable"
find "$REPO_ROOT/config/hypr/scripts"  -type f -exec chmod +x {} \; 2>/dev/null || true
find "$REPO_ROOT/config/waybar/scripts" -type f -exec chmod +x {} \; 2>/dev/null || true
find "$REPO_ROOT/config/rofi/scripts"  -type f -exec chmod +x {} \; 2>/dev/null || true
info "scripts marked executable"

# ── 5b. User helper scripts → ~/.local/bin ──
echo
echo "==> Installing user helper scripts into ~/.local/bin"
mkdir -p "$HOME/.local/bin"
for helper in "$REPO_ROOT/bin"/*; do
    [ -f "$helper" ] || continue
    case "$helper" in
        *.patch) warn "skip $(basename "$helper") (patch, not a helper script)"; continue ;;
    esac
    cp -p "$helper" "$HOME/.local/bin/$(basename "$helper")"
    chmod +x "$HOME/.local/bin/$(basename "$helper")"
    info "helper: $(basename "$helper")"
done

# ── 5c. Rofi image-carousel theme ────────────
echo
echo "==> Installing rofi image-carousel theme"
ROFI_SRC="$REPO_ROOT/config/rofi/themes/active-image-carousel.rasi"
ROFI_DST="$HOME/.config/rofi/themes/active-image-carousel.rasi"
mkdir -p "$HOME/.config/rofi/themes"
if [ -f "$ROFI_SRC" ]; then
    # rofi is symlinked to the repo, so the source may already BE the target —
    # cp would fail with "same file" and abort the whole install under set -e.
    if [ "$ROFI_SRC" -ef "$ROFI_DST" ]; then
        info "rofi image-carousel theme already in place (repo is symlinked)"
    else
        cp -p "$ROFI_SRC" "$ROFI_DST"
        info "rofi image-carousel theme installed"
    fi
else
    warn "rofi image-carousel theme not found in repo"
fi

# ── 5d. Rofimoji themes → ~/.local/share/rofimoji ──
echo
echo "==> Installing rofimoji themes"
ROFIMOJI_SRC="$REPO_ROOT/rofimoji/themes"
ROFIMOJI_DST="$HOME/.local/share/rofimoji/themes"
if [ -d "$ROFIMOJI_SRC" ]; then
    mkdir -p "$ROFIMOJI_DST"
    cp -p "$ROFIMOJI_SRC"/*.rasi "$ROFIMOJI_DST/" 2>/dev/null || true
    info "rofimoji themes installed ($(ls "$ROFIMOJI_DST"/*.rasi 2>/dev/null | wc -l) files)"
else
    warn "rofimoji themes not found in repo"
fi

# ── 6. Initial palette ───────────────────────
echo
echo "==> Generating initial color palette"
if command -v matugen >/dev/null 2>&1; then
    WALL="$(find "$WALL_DST/$THEME_LOWER" -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' \) 2>/dev/null | sort | head -n 1)"
    if [ -n "$WALL" ]; then
        matugen image "$WALL" -c "$HOME/.config/matugen/config.toml" --source-color-index 0 \
            && info "palette generated from $WALL" \
            || warn "matugen failed, run it manually after first login"
    else
        warn "no wallpaper found for theme '$THEME_LOWER'"
    fi
    else
        warn "matugen not installed; palette will be generated on first theme switch"
    fi

    # ── 6b. Package list restore (fresh machines) ──
    # Installed per-package: one conflict/broken build must not abort the rest.
    echo
    echo "==> Restoring packages from pkglist (if present)"
    if [ -f "$REPO_ROOT/pkglist/native.txt" ]; then
        # shellcheck disable=SC2086
        MISSING="$(comm -23 <(pkglist_lines "$REPO_ROOT/pkglist/native.txt") <(pacman -Qqe | sort) | tr '\n' ' ')"
        if [ -n "$MISSING" ]; then
            if [ "$SUDO_OK" -eq 1 ]; then
            info "installing $(printf '%s' "$MISSING" | wc -w) missing repo packages"
            # shellcheck disable=SC2086
            install_pkgs "sudo pacman -S" $MISSING
            else
                warn "no sudo — skipping repo package install:$MISSING"
            fi
        else
            info "all pkglist repo packages already installed"
        fi
    else
        warn "pkglist/native.txt not found, skipping restore"
    fi
    if [ -f "$REPO_ROOT/pkglist/foreign.txt" ]; then
        if command -v yay >/dev/null 2>&1; then
            # shellcheck disable=SC2086
            MISSING_AUR="$(comm -23 <(pkglist_lines "$REPO_ROOT/pkglist/foreign.txt") <(pacman -Qqm | sort) | tr '\n' ' ')"
            if [ -n "$MISSING_AUR" ]; then
                if [ "$SUDO_OK" -eq 1 ]; then
                info "installing $(printf '%s' "$MISSING_AUR" | wc -w) missing AUR packages"
                # shellcheck disable=SC2086
                install_pkgs "yay -S" $MISSING_AUR
                else
                    warn "no sudo — skipping AUR package install:$MISSING_AUR"
                fi
            else
                info "all pkglist AUR packages already installed"
            fi
        else
            warn "yay not installed, skipping AUR restore"
        fi
    fi
    if [ -n "$FAILED_PKGS" ]; then
        warn "these packages need manual attention (conflict/build error):$FAILED_PKGS"
        # shellcheck disable=SC2086
        warn "retry with: yay -S --needed $FAILED_PKGS"
    fi
    mkdir -p "$REPO_ROOT/pkglist"
    pacman -Qqen > "$REPO_ROOT/pkglist/native.txt"
    pacman -Qqem > "$REPO_ROOT/pkglist/foreign.txt"
    info "package lists refreshed (commit them to keep the backup current)"

    # ── 6c. System resilience services ──
    echo
    echo "==> Enabling resilience services (ufw, cronie, powertop)"
    if [ "$SUDO_OK" -eq 1 ]; then
    sudo ufw default deny incoming >/dev/null 2>&1 || true
    sudo ufw default allow outgoing >/dev/null 2>&1 || true
    sudo ufw --force enable >/dev/null 2>&1 && info "ufw active" || warn "ufw enable skipped"
    sudo systemctl enable --now cronie >/dev/null 2>&1 && info "cronie active" || warn "cronie skipped"
    if [ -f "$REPO_ROOT/scripts/systemd/powertop.service" ]; then
        sudo cp -p "$REPO_ROOT/scripts/systemd/powertop.service" /etc/systemd/system/powertop.service
        sudo systemctl daemon-reload
        sudo systemctl enable --now powertop >/dev/null 2>&1 && info "powertop autotune active" || warn "powertop skipped"
    fi
    if ! pacman -Q timeshift >/dev/null 2>&1; then
        sudo pacman -S --noconfirm --needed timeshift || warn "timeshift install skipped (ext4 snapshots need it)"
    fi
    else
        warn "no sudo — skipping ufw/cronie/powertop/timeshift (re-run with sudo access to enable)"
    fi

    # ── 7. Default image viewer ──────────────
    echo
    echo "==> Setting default image viewer (imv)"
    if [ "$SUDO_OK" -eq 1 ]; then
    sudo pacman -S --noconfirm --needed imv >/dev/null 2>&1 || warn "imv install skipped"
    else
        warn "no sudo — skipping imv install"
    fi
    if [ -f "$HOME/.config/mimeapps.list" ]; then
        sed -i 's#=org\.gnome\.eog\.desktop#=imv.desktop#g; s#=eog\.desktop#=imv.desktop#g' "$HOME/.config/mimeapps.list"
        for m in image/jpeg image/png image/gif image/webp image/bmp image/x-ms-bmp image/tiff; do
            xdg-mime default imv.desktop "$m" 2>/dev/null || true
        done
        info "image MIME types set to imv.desktop"
    else
        warn "~/.config/mimeapps.list not found; image MIME defaults unchanged"
    fi

    echo
    echo "Done. Log out and select Hyprland at the greeter (or start it) to use the new setup."
if [ -d "$BACKUP_DIR" ]; then
    echo "Backups of replaced files are in: $BACKUP_DIR"
fi
exit 0
