-- Wallpaper-synced theme: tokyonight recolored from matugen output.
-- The `matugen-colors` module is GENERATED by matugen on every wallpaper
-- change (templates/nvim.lua -> ~/.config/nvim/lua/matugen-colors.lua).
-- It is deliberately NOT vendored in modules/: activation rsync would
-- otherwise overwrite the live colors with a stale copy on each rebuild.
-- Before the first matugen run (pcall fails) this is a no-op and LazyVim
-- keeps its tokyonight default from plugins/colorscheme.lua.
-- Wallpaper-synced theme: tokyonight recolored from matugen output.
-- The `matugen-colors` module is GENERATED by matugen on every wallpaper
-- change (templates/nvim.lua -> ~/.config/nvim/lua/matugen-colors.lua).
-- Mapping follows ghostty.conf so nvim matches terminal/waybar:
--   red=error, green=tertiary, yellow=secondary, blue=primary,
--   magenta=tertiary_fixed, cyan=primary_fixed.
return {
  {
    "folke/tokyonight.nvim",
    opts = function(_, opts)
      local ok, m = pcall(require, "matugen-colors")
      if not ok or type(m) ~= "table" or type(m.colors) ~= "table" then
        return
      end
      local c = m.colors
      local primary = c.primary
      local primary_fixed = c.primary_fixed or c.primary
      local secondary = c.secondary
      local secondary_fixed = c.secondary_fixed or c.secondary
      local tertiary = c.tertiary
      local tertiary_fixed = c.tertiary_fixed or c.tertiary
      local error = c.error
      local function lighten(hex, amt)
        if type(hex) ~= "string" then
          return hex
        end
        local r = tonumber(hex:sub(2, 3), 16)
        local g = tonumber(hex:sub(4, 5), 16)
        local b = tonumber(hex:sub(6, 7), 16)
        if not (r and g and b) then
          return hex
        end
        local function up(v)
          return math.floor(v + (255 - v) * amt + 0.5)
        end
        return string.format("#%02x%02x%02x", up(r), up(g), up(b))
      end
      opts.on_colors = function(colors)
        -- base
        if c.bg then
          colors.bg = c.bg
          colors.bg_dark = c.bg_dark or c.bg
          colors.bg_float = c.surface or c.bg
          colors.bg_highlight = c.surface_high or c.surface or c.bg
          colors.bg_popup = c.surface or c.bg
          colors.bg_search = c.surface or c.bg
          colors.bg_sidebar = c.bg
          colors.bg_statusline = c.bg
          colors.bg_visual = c.surface_high or c.surface_variant or c.surface or c.bg
          colors.black = c.bg_dark or c.bg
          colors.terminal_black = c.bg_dark or c.bg
        end
        if c.fg then
          colors.fg = c.fg
          colors.fg_dark = c.on_surface_variant or c.fg
          colors.fg_float = c.fg
          colors.fg_sidebar = c.fg
          colors.fg_gutter = c.outline or c.fg
        end
        if c.outline then
          colors.border = c.outline
          colors.border_highlight = primary or c.outline
          colors.comment = c.outline
          colors.dark3 = c.outline
          colors.dark5 = c.outline_variant or c.outline
        end
        -- accents (match ghostty/terminal)
        if primary then
          colors.blue = primary
          colors.blue0 = primary
          colors.blue1 = primary_fixed or primary
          colors.blue2 = c.inverse_surface or primary
          colors.blue5 = primary
          colors.blue6 = primary
          colors.blue7 = c.outline_variant or primary
          colors.info = primary
          colors.hint = primary
        end
        if primary_fixed then
          colors.cyan = primary_fixed
          colors.teal = primary_fixed
        end
        if tertiary then
          colors.green = tertiary
          colors.green1 = tertiary
          colors.green2 = tertiary
        end
        if secondary then
          colors.yellow = secondary
          colors.warning = secondary
        end
        if secondary_fixed then
          colors.orange = secondary_fixed
        elseif secondary then
          colors.orange = secondary
        end
        if tertiary_fixed then
          colors.magenta = tertiary_fixed
          colors.magenta2 = tertiary_fixed
          colors.purple = tertiary_fixed
          colors.todo = tertiary_fixed
        elseif tertiary then
          colors.magenta = tertiary
          colors.magenta2 = tertiary
          colors.purple = tertiary
        end
        if error then
          colors.red = error
          colors.red1 = error
          colors.error = error
        end
        -- vcs / diff follow same accents
        colors.git = colors.git or {}
        if tertiary then
          colors.git.add = tertiary
        end
        if primary then
          colors.git.change = primary
        end
        if error then
          colors.git.delete = error
        end
        if type(colors.diff) == "table" then
          if tertiary then
            colors.diff.add = tertiary
          end
          if primary then
            colors.diff.change = primary
          end
          if error then
            colors.diff.delete = error
          end
          colors.diff.text = primary_fixed or primary
        end
      end
      opts.on_highlights = function(hl)
        -- Stylesheet keys brighter than values: with near-monochrome
        -- wallpapers Type (keys) and Constant (values) land on almost
        -- identical grays, so lift the key groups toward white. cssProp
        -- covers every css*Prop link; @property covers treesitter CSS
        -- if a parser is ever installed.
        if primary then
          local key = lighten(primary, 0.45)
          hl.cssProp = { fg = key }
          hl["@property"] = { fg = key }
        end
      end
    end,
  },
}
